version: '2.1'
services:
  rabbitmq:
    #image: rabbitmq:3-management
    image: rabbitmq
    restart: always
    ports:
      - 15672:15672
    #  - 5672:5672
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  config:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
#    image: 192.168.2.112:5000/piggymetrics-config:stable
    image: 10.23.27.6:443/piggymetrics-config:stable
    restart: always
    ports:
      - 8888:8888
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  registry:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: 10.23.27.6:443/piggymetrics-registry:stable
#    image: 192.168.2.112:5000/piggymetrics-registry:stable
    restart: always
    depends_on:
      config:
        condition: service_healthy
    ports:
      - 8761:8761
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  gateway:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: 10.23.27.6:443/piggymetrics-gateway:stable
#    image: 192.168.2.112:5000/piggymetrics-gateway:stable
    restart: always
    depends_on:
      config:
        condition: service_healthy
    ports:
      - 80:4000
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  auth-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      NOTIFICATION_SERVICE_PASSWORD: $NOTIFICATION_SERVICE_PASSWORD
      STATISTICS_SERVICE_PASSWORD: $STATISTICS_SERVICE_PASSWORD
      ACCOUNT_SERVICE_PASSWORD: $ACCOUNT_SERVICE_PASSWORD
      MONGODB_PASSWORD: $MONGODB_PASSWORD
    image: 10.23.27.6:443/piggymetrics-auth-service:stable
#    image: 192.168.2.112:5000/piggymetrics-auth-service:stable
    restart: always
    ports:
      - 5000:5000
    depends_on:
      config:
        condition: service_healthy
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  auth-mongodb:
    environment:
      MONGODB_PASSWORD: $MONGODB_PASSWORD
    image: 10.23.27.6:443/piggymetrics-mongodb:stable
#    image: 192.168.2.112:5000/piggymetrics-mongodb:stable
    restart: always
    ports:
      - 25000:27017
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  account-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      ACCOUNT_SERVICE_PASSWORD: $ACCOUNT_SERVICE_PASSWORD
      MONGODB_PASSWORD: $MONGODB_PASSWORD
    image: 10.23.27.6:443/piggymetrics-account-service:stable
#    image: 192.168.2.112:5000/piggymetrics-account-service:stable
    restart: always
    ports:
      - 6000:6000
    depends_on:
      config:
        condition: service_healthy
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  account-mongodb:
    environment:
      INIT_DUMP: account-service-dump.js
      MONGODB_PASSWORD: $MONGODB_PASSWORD
    image: 10.23.27.6:443/piggymetrics-mongodb:stable
#    image: 192.168.2.112:5000/piggymetrics-mongodb:stable
    restart: always
    ports:
      - 26000:27017
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  statistics-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      MONGODB_PASSWORD: $MONGODB_PASSWORD
      STATISTICS_SERVICE_PASSWORD: $STATISTICS_SERVICE_PASSWORD
    image: 10.23.27.6:443/piggymetrics-statistics-service:stable
#    image: 192.168.2.112:5000/piggymetrics-statistics-service:stable
    restart: always
    ports:
      - 7000:7000
    depends_on:
      config:
        condition: service_healthy
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  statistics-mongodb:
    environment:
      MONGODB_PASSWORD: $MONGODB_PASSWORD
    image: 10.23.27.6:443/piggymetrics-mongodb:stable
#    image: 192.168.2.112:5000/piggymetrics-mongodb:stable
    restart: always
    ports:
      - 27000:27017
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  notification-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      MONGODB_PASSWORD: $MONGODB_PASSWORD
      NOTIFICATION_SERVICE_PASSWORD: $NOTIFICATION_SERVICE_PASSWORD
    image: 10.23.27.6:443/piggymetrics-notification-service:stable
#    image: 192.168.2.112:5000/piggymetrics-notification-service:stable
    restart: always
    ports:
      - 8000:8000
    depends_on:
      config:
        condition: service_healthy
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  notification-mongodb:
    image: 10.23.27.6:443/piggymetrics-mongodb:stable
#    image: 192.168.2.112:5000/piggymetrics-mongodb:stable
    restart: always
    ports:
      - 28000:27017
    environment:
      MONGODB_PASSWORD: $MONGODB_PASSWORD
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  monitoring:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: 10.23.27.6:443/piggymetrics-monitoring:stable
#    image: 192.168.2.112:5000/piggymetrics-monitoring:stable
    restart: always
    depends_on:
      config:
        condition: service_healthy
    ports:
      - 9000:8080
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  turbine-stream-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: 10.23.27.6:443/piggymetrics-turbine-stream-service:stable
#    image: 192.168.2.112:5000/piggymetrics-turbine-stream-service:stable
    restart: always
    depends_on:
      config:
        condition: service_healthy
    ports:
    - 8989:8989
    logging:
      options:
        max-size: "10m"
        max-file: "10"