#!/bin/bash

#a=$(sudo docker ps | grep petclinic | cut -d' ' -f 1)
#sudo docker stop $a
docker pull 192.168.2.112:5000/piggymetrics-config:latest
docker pull 192.168.2.112:5000/piggymetrics-registry
docker pull 192.168.2.112:5000/piggymetrics-gateway
docker pull 192.168.2.112:5000/piggymetrics-auth-service
docker pull 192.168.2.112:5000/piggymetrics-mongodb
docker pull 192.168.2.112:5000/piggymetrics-account-service
docker pull 192.168.2.112:5000/piggymetrics-statistics-service
docker pull 192.168.2.112:5000/piggymetrics-notification-service
docker pull 192.168.2.112:5000/piggymetrics-monitoring
docker pull 192.168.2.112:5000/piggymetrics-turbine-stream-service

docker-compose -f docker-compose.yml -f docker-compose.dev.yml up
